### Using GPUs

In [3]:
import tensorflow as tf
tf.reset_default_graph()
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3,2], name='b')
c = tf.matmul(a,b)
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess.run(c))

[[22. 28.]
 [49. 64.]]


### Core API

In [6]:
import tensorflow as tf
tf.reset_default_graph()
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)
total = a + b
print(a.op)
print(b.op)
print(total.op.inputs)

name: "Const"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 3.0
    }
  }
}

name: "Const_1"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 4.0
    }
  }
}



In [8]:
tf.reset_default_graph()
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
with tf.Session() as sess:
    print(sess.run(vec))
    print(sess.run(vec))
    print(sess.run((out1,out2)))

[0.69538355 0.3705659  0.32879615]
[0.5676142 0.73999   0.6959772]
(array([1.6344695, 1.6742139, 1.1478678], dtype=float32), array([2.6344695, 2.674214 , 2.1478677], dtype=float32))


In [10]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [11]:
with tf.Session() as sess:
    print(sess.run(z,feed_dict={x:3,y:4.5}))
    print(sess.run(z,feed_dict={x:[1,3],y:[2,4]}))
    

7.5
[3. 7.]


In [13]:
my_data = [[0,1],[2,3],[4,5],[6,7]]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()
with tf.Session() as sess:
    while True:
        try:
            print(sess.run(next_item))
        except tf.errors.OutOfRangeError:
            break

[0 1]
[2 3]
[4 5]
[6 7]


In [15]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()
with tf.Session() as sess:
    sess.run(iterator.initializer)
    while True:
        try:
            print(sess.run(next_row))
        except tf.errors.OutOfRangeError:
            break

[ 0.7097742  -0.27966222  0.11903027]
[ 0.1793734  -0.29594883  1.0311455 ]
[ 0.28888628 -0.9233624   0.00490942]
[-0.96602464 -2.189392   -0.54954314]
[-0.03894538 -0.9798314   0.17050374]
[-1.0547564  -0.08528162 -2.3525438 ]
[-1.9843653 -1.3317318  1.9374261]
[ 0.21580118 -0.84848905 -0.42688802]
[ 1.2307706  -0.07531051 -0.2868658 ]
[0.84262043 0.21179587 0.20960817]


### Layers 

In [17]:
import tensorflow as tf
tf.reset_default_graph()
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(y,{x:[[1,2,3],[4,5,6]]}))
    

[[-2.8819385]
 [-7.281698 ]]


In [20]:
tf.reset_default_graph()
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))
print(sess.run(inputs))


[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]
